### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by yuchunmiao98** [Jendker/inverse_rl_dexterous_hand#1]
When I install, a problem is always occurring: Could not find a version that satisfies the requirement mjrl@ git+https://github.com/Jendker/mjrl.git (from inverse-rl-dexterous-hand==0.0.1) (from versions: )
No matching distribution found for mjrl@ git+https://github.com/Jendker/mjrl.git (from inverse-rl-dexterous-hand==0.0.1)

**Comment by jborbik** [comment]
Try updating pip to a newer version. There are no issues on pip 21.3.1.

**Comment by yuchunmiao98** [comment]
Thanks so much! This problem has been solved in anaconda environment. The procedure can run on my pc now. Thanks again for your patience.
















At 2021-12-13 05:55:31, "Jędrzej Beniamin Orbik" ***@***.***> wrote:

Try updating pip to a newer version. There are no issues on pip 21.3.1.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
